Impelement get_homogeneous_pages.
djrobstep/sqlakeyset pull request #87
Opened 2023-07-11 19:02 UTC by mattalbr

Unit tests forthcoming once we're directionally aligned.

2023-07-11 19:02 UTC, mattalbr commented
#86

2023-07-12 00:06 UTC, acarapetis requested changes

2023-07-12 00:06 UTC, acarapetis commented on sqlakeyset/paging.py
CI fails at flake8 with a bunch of undefined names - looks like you've forgotten some imports?

2023-07-12 00:06 UTC, acarapetis commented on sqlakeyset/paging.py
> +def get_homogeneous_page(queries: list[PageRequest[_TP]]) -> list[Page[Row[_TP]]]:
I definitely think it should be get_homogeneous_page**s**.

2023-07-12 00:40 UTC, acarapetis commented
I definitely think some version of this is worth including, since it's not achievable using our current documented public API; so thanks!

I've added a bunch of minor comments in my review above, should be easy fixes. I do have a couple more significant concerns:

- Since the `Query` API is now considered legacy, I definitely think we want an equivalent `select_homogeneous_pages` API to work with `Select`.
- Unless I'm mistaken, the `_page_identifier` column is going to be hanging around on the rows returned to the user, which is not desirable. We already handle this same issue for added keyset columns in `orm_page_from_rows`, so hopefully we just need to add an additional item to `paging_query.extra_columns` - let me know if you need help with this.

And yeah, bring on the tests. :)

2023-07-14 19:26 UTC, mattalbr reviewed
I'm almost there, just still struggling with select_homogeneous_pages. It keeps failing trying to grab the keys. Let me know if you see something obvious, otherwise I'll keep fighting with it.

Otherwise, good for you to take another look.

2023-07-20 23:11 UTC, mattalbr commented
Closing in favor of #90 which I finally got working for both ORM and select.

2023-07-20 23:11 UTC, closed without merging